version: 2.1

orbs:
  go: circleci/go@1.7

parameters:
  go-version:
    type: string
    default: '1.17.1'

executors:
  node:
    docker:
      - image: node:16
  python:
    docker:
      - image: python:3.9-bullseye
  ubuntu-machine:
    machine:
     image: ubuntu-2004:202107-02

commands:
  install-deps-apt:
    parameters:
      sudo:
        type: boolean
        default: true
    steps:
      - run:
          name: Update package indexes
          command: <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get -q update
      - run:
          name: Install singularity dependencies
          command: <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get -q install -y build-essential squashfs-tools libseccomp-dev libssl-dev uuid-dev cryptsetup-bin libgpgme-dev
  install-latex-apt:
    parameters:
        sudo:
          type: boolean
          default: true
    steps:
      - run:
          name: Install LaTeX environment
          command: <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get -q install -y texlive-latex-extra latexmk
  install-deps-python:
    parameters:
      sudo:
        type: boolean
        default: true
    steps:
      - run:
          name: Install python dependencies
          command: <<# parameters.sudo >>sudo <</ parameters.sudo >>pip install sphinx sphinx-rtd-theme rstcheck pygments
  init-submodules:
    steps:
      - run:
          name: Initialize git submodules
          command: git submodule update --init --recursive

jobs:
  lint_markdown:
    executor: node
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

  check_rst:
    executor: python
    steps:
      - checkout
      - install-deps-python:
         sudo: false
      - run:
          name: Lint rst
          command: |
            rstcheck --ignore-language c,c++ --report warning *.rst

  make_html:
    executor: ubuntu-machine
    steps:
      - checkout
      - install-deps-apt
      - install-deps-python
      - go/install:
          version: << pipeline.parameters.go-version >>
      - init-submodules  
      - run:
          name: make html
          command: |
            make html
      - store_artifacts:
          path: _build/html
          destination: html

  make_pdf_epub:
    executor: ubuntu-machine
    steps:
      - checkout
      - install-deps-apt
      - install-latex-apt
      - install-deps-python
      - go/install:
          version: << pipeline.parameters.go-version >>
      - init-submodules  
      - run:
          name: make pdf
          command: |
            make latexpdf
      - store_artifacts:
          path: _build/latex
          destination: pdf
      - run:
          name: make epub
          command: |
            make epub
      - store_artifacts:
          path: _build/epub
          destination: epub

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_markdown
      - check_rst
      - make_html:
          requires:
            - check_rst
      - make_pdf_epub:
          requires:
            - check_rst
